name: "Joe O'Reilly"
description: ""

url: "http://localhost:4000"
# url: "www.joeoreilly.co.uk"

paginate: 10
paginate_path: "blog/page:num"

markdown: rdiscount

permalink: pretty

highlighter: rouge

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed